### ISSUE TITLE
Bug when tamer exits after committing offset

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#211]
https://github.com/laserdisc-io/tamer/blob/2ab1962dbaabe532f49a980e63bbce5e04ff8c90/core/src/main/scala/tamer/kafka/Kafka.scala#L102

There might be an edge case when there is only one message and the program is stuck waiting for other states at startup before proceeding (in the `plainStream` instruction). I will try to reproduce this later, this is just a note.

**Comment by gurghet** [comment]
So far it seems that this is really caused by tamer committing the latest offset when exiting. It's still not clear when this happens in the first place. Normally when tamer exits the latest offset in uncommitted, meaning the state was written but it was not read.

**Comment by gurghet** [comment]
I presume this is solved as well since it should not be possible to move the offset without providing a valid (as in not aborted) state.

**Comment by sirocchj** [comment]
Fixed by #520
