### ISSUE TITLE
use nanoTime instead of wall clock time to guarantee monotonicity

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#213]
The reason is nanoTime gives you a monotonic value (representing the number of nanoseconds since system boot) while instant gives you a non-monotonic value (millis since epoch). The latter is subject to changes made to the system clock (including it going backwards), usually as result of NTP adjustments. See also https://medium.com/@kralka/its-about-time-d42e68dbe1df

_Originally posted by @sirocchj in https://github.com/laserdisc-io/tamer/pull/212#discussion_r549566406_

**Comment by sirocchj** [comment]
This is now fixed as of `v0.9.0`.

See https://github.com/laserdisc-io/tamer/blob/c7e5868d91a2210ea572537ccd9083f4b9c43233/db/src/main/scala/tamer/db/model.scala and https://github.com/laserdisc-io/tamer/blob/8613425692497525ca11c9be98d9aa8f8da5d0d2/db/src/main/scala/tamer/db/DbSetup.scala#L58-L60
