### ISSUE TITLE
Add S3 tags and update github description

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#239]
I noticed there are no S3 tags and the descriptions says "Standalone alternative to Kafka JDBC Connector"
I propose to update it to "Standalone alternative to Kafka JDBC Connector and S3 Kafka Connector"

**Comment by sirocchj** [comment]
Amended description, left it more general as we intend provide more than just doobie and s3

**Comment by gurghet** [comment]
Awesome!
