### ISSUE TITLE
Field never used in core

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#420]
The field below, while logically belongs to core, it's never used by it and only used by the modules. This is just code smell and not a real problem but might indicate there is a better way to structure the code.
https://github.com/laserdisc-io/tamer/blob/4af203cff31c36e41b1cbca507c17ca3a1bc4b4f/core/src/main/scala/tamer/Setup.scala#L12
It means it's possible to do things like override `Setup` and
```
override val recordKey: (State, LastAlertTime) => LastAlertTimeKey = ???
```
and make the code still work because you are using a different way to create your record key.

**Comment by sirocchj** [comment]
This is now addressed in #1391
