### ISSUE TITLE
Offset update should guarantee all elements have been pushed

### ISSUE THREAD

**Issue by sirocchj** [laserdisc-io/tamer#43]
It currently could be [updated](https://github.com/laserdisc-io/tamer/blob/dfcbcd242ae6e1335173091b77de85bf1db34abc/core/src/main/scala/tamer/kafka/Kafka.scala#L136-L140) before the [last batch](https://github.com/laserdisc-io/tamer/blob/dfcbcd242ae6e1335173091b77de85bf1db34abc/core/src/main/scala/tamer/kafka/Kafka.scala#L100-L105) (in queue) has been published to Kafka. Likely solvable with a semaphore

**Comment by gurghet** [comment]
This is kinda solved by convention. We force it like this or the fiber dies.

**Comment by sirocchj** [comment]
Fixed by #520
