### ISSUE TITLE
Add checks for consistency of topic

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#541]
After #540 there are no more checks of the state topic in case of crashes. On one hand the cases are greatly reduced by the introduction of transactionality, on the other this does nothing to prevent external factors (wrong number of replicas or simply external producers to the topic).
We could add an invariant check, that not only checks the topic for consistency on start up, but also continuously monitors the number of messages read and stops in case more than one message is in the buffer.

**Comment by sirocchj** [comment]
I believe this is addressed in large by #1385
