### ISSUE TITLE
TamerError leakage

### ISSUE THREAD

**Issue by gurghet** [laserdisc-io/tamer#565]
https://github.com/laserdisc-io/tamer/blob/0a539b788976e932874dc8ce130ed1930f74d975/core/src/main/scala/tamer/Setup.scala#L18

https://github.com/laserdisc-io/tamer/blob/0a539b788976e932874dc8ce130ed1930f74d975/core/src/main/scala/tamer/Setup.scala#L16

Here `TamerError` leaks to the user, a quick and dirty solution would be to widen to a `RIO`

**Comment by sirocchj** [comment]
Fixed in #1377
